### ISSUE TITLE
Just a few questions

### ISSUE THREAD

**Issue by g3yt** [coolfren/funkiin#1]
Hey, I had a few questions about how this port will work with the way that stages are charted. Will the stages be charted using the actual json files? Or will you need to manually enter in where the notes are supposed to be? For example, the [Ps1 port](https://github.com/cuckydev/PSXFunkin) of fnf uses the actual json files from fnf, but the creator of the [Fnf psp port](https://gamejolt.com/games/FNFFORPSP/598364) manually enters the notes in. If it is like how the ps1 port of fnf does it I feel like that will be way easier to mod the game (I’ve modded the fnf ps1 port before). Thank you for reading this.

**Comment by coolfren** [comment]
late but 
>will the stages be charted using actual json files?
no because handling json files in any non OOP language is a pain so i'll have the charts manually in with their own headers which basically have their own constant array.
